name: Build and Push on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      # OCI AUTH
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: us-ashburn-1
      # IMAGE VARS
      IMAGE_NAME: corrino-devops-repository/nvidia-vss-oci
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.3.0
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      
      - name: Compute short SHA
        id: short-sha
        run: echo "value=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        run: |
          docker build -t "${{ env.IMAGE_NAME }}":pr-${{ steps.short-sha.outputs.value }} -f ./Dockerfile .

      - name: Tag and Push Docker Image
        env:
          IMAGE_REMOTE: "iad.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ env.IMAGE_NAME }}"
        run: |
          docker tag "${{ env.IMAGE_NAME }}:pr-${{ steps.short-sha.outputs.value }}" "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"
          docker push "${{ env.IMAGE_REMOTE }}:pr-${{ steps.short-sha.outputs.value }}"